_BASE_: maskformer/maskformer_R50_bs16_160k_dino.yaml
TOTAL_ITER: 40000
MODEL: 
   META_ARCHITECTURE: "ONEMATRIX" # "UNET" or "MaskFormer" or "ONEMATRIX"
   ONEMATRIX:
    N_CLASSES: 4
    BILINEAR: True
   UNET:
    N_CHANNELS: 3
    N_CLASSES: 4
    BILINEAR: True
   MASK_FORMER:
    NUM_OBJECT_QUERIES: 4
GWM:
  # MODEL: "UNET"
  FOCUS_SERIES: "00007"
  STABLE_SEED: True
  RESOLUTION: (192,352)
  FLOW_RES: (192,352)
  DATASET: "DAVIS"
  REBOOST_WHEN_DECREASE: False
  LOSS_MULT:
    GLOBAL: 100000000000.0
    OPT: 0.03
    TRAJ: 0.00005
SOLVER:
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 1