_BASE_: maskformer/maskformer_R50_bs16_160k_dino.yaml
MODEL: 
   META_ARCHITECTURE: "UNET" # "UNET" or "MASKFORMER" or "ONEMATRIX"
  #  ONEMATRIX:
  #   N_CLASSES: 4
  #   BILINEAR: True
   UNET:
    N_CHANNELS: 3
    N_CLASSES: 2
    BILINEAR: True
   MASK_FORMER:
    NUM_OBJECT_QUERIES: 2
GWM:
  # MODEL: "UNET"
  STABLE_SEED: True
  RESOLUTION: (192,352)
  FLOW_RES: (192,352)
  DATASET: "DAVIS"
  REBOOST_WHEN_DECREASE: False
  LOSS_MULT:
    OPT: 0.00015
    TRAJ: 0.1
SOLVER:
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 8