_BASE_: maskformer/maskformer_R50_bs16_160k_dino.yaml
MODEL: 
  #  META_ARCHITECTURE: "UNET"
  #  UNET:
  #   N_CHANNELS: 3
  #   N_CLASSES: 25
  #   BILINEAR: True
   MASK_FORMER:
    NUM_OBJECT_QUERIES: 4
GWM:
  # MODEL: "UNET"
  # RESOLUTION: (32,32)
  # FLOW_RES: (32,32)
  DATASET: "DAVIS"
  LOSS_MULT:
    OPT: 0.03
    TRAJ: 0.1
SOLVER:
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 4