_BASE_: maskformer_R50_bs16_160k_dino.yaml
MODEL: 
   META_ARCHITECTURE: "UNET"
   UNET:
    N_CHANNELS: 3
    N_CLASSES: 25
    BILINEAR: True
   MASK_FORMER:
    NUM_OBJECT_QUERIES: 25
GWM:
  MODEL: "UNET"
  RESOLUTION: (32,32)
  FLOW_RES: (32,32)
  LOSS_MULT:
    REC: 0.03
    OPT: 0.003
    DIV: 0.000000001
SOLVER:
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 8